- updated for 1.5.0
Changed files:
    VirtualBox-configure.patch -> 1.4
    VirtualBox-qt-paths.patch -> 1.4

diff --git a/VirtualBox-configure.patch b/VirtualBox-configure.patch
--- a/VirtualBox-configure.patch
+++ b/VirtualBox-configure.patch
@@ -1,13 +1,13 @@
 --- configure.orig	2007-08-23 21:34:25.000000000 +0200
 +++ configure	2007-08-23 21:39:54.000000000 +0200
 @@ -57,7 +57,6 @@
- CFLAGSHAL="-I/usr/include/hal -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include"
- LIBPATHHAL=""
- LIBHAL="-lhal -ldbus-1"
--QTDIR="/usr/qt/3 /usr/lib/qt3 /usr/lib/qt-3.3 /usr/share/qt3 /usr/lib64/qt-3.3"
+ LIBZ="-lz"
+ INCPNG=""
+ LIBPNG="-lpng"
+-QTDIR="/usr/qt/3 /usr/lib/qt3 /usr/lib/qt-3.3 /usr/share/qt3 /usr/lib64/qt-3.3 /usr/X11R6"
  KBUILDDIR="`cd $(dirname $0); pwd`/kBuild"
  DEVDIR="`cd $(dirname $0); pwd`/tools"
- if [ -d /lib/modules/`uname -r`/build ]; then
+ if [ -d "/lib/modules/`uname -r`/build" ]; then
 @@ -167,8 +166,8 @@
    echo "compiling the following source file:" >> $LOG
    cat .tmp_src.cc >> $LOG
@@ -16,12 +16,12 @@
 -  $CXX -O -Wall -o .tmp_out .tmp_src.cc $1 >> $LOG 2>&1
 +  echo "$CXX -O -Wall -o .tmp_out .tmp_src.cc -L/usr/X11R6/lib \"$1\"" >> $LOG
 +  $CXX -O -Wall -o .tmp_out .tmp_src.cc -L/usr/X11R6/lib $1 >> $LOG 2>&1
-   if (($?!=0)); then
+   if [ $? -ne 0 ]; then
      if [ -z "$4" ]; then
-       echo -e "\n  $2 not found at $1 or $3 headers not found"
-@@ -873,37 +872,26 @@
+       echo
+@@ -873,38 +872,27 @@
  }
- ' > .tmp_src.cc
+ EOF
    found_qt=0
 -  libs="lib"
 -  [ "$LIB" = "lib64" ] && libs="$libs lib64"
@@ -37,7 +37,7 @@
 +  echo "$CXX -O -Wall -o .tmp_out .tmp_src.cc -I/usr/include/qt -L/usr/lib -lqt-mt" >> $LOG
      
 -      $CXX -O -Wall -o .tmp_out .tmp_src.cc -I$q/include -L$q/$l -lqt-mt >> $LOG 2>&1
--      if (($?==0)); then
+-      if [ $? -eq 0 ]; then
 -        if test_execute; then
 -          cnf_append "QTDIR" "`cd $q ; pwd`"
 -          found_qt=1
@@ -45,19 +45,20 @@
 -        fi
 -      fi
 -    done
--    if (($found_qt==1)); then
+-    if [ $found_qt -eq 1 ]; then
 -      break
 +  $CXX -O -Wall -o .tmp_out .tmp_src.cc -I/usr/include/qt -L/usr/lib -lqt-mt >> $LOG 2>&1
-+  if (($?==0)); then
++  if [ $? -eq 0 ]; then
 +    if test_execute; then
 +      found_qt=1
      fi
 -  done
 +  fi
-   if (($found_qt!=1)); then
--    echo -e "\n  Qt not found at \"$QTDIR\" or Qt headers not found"
-+    echo -e "\n  Qt not found or Qt headers not found"
-     echo      "  Check the file $LOG for detailed error information."
+   if [ $found_qt -ne 1 ]; then
+     echo
+-    echo "  Qt not found at \"$QTDIR\" or Qt headers not found"
++    echo "  Qt not found or Qt headers not found"
+     echo "  Check the file $LOG for detailed error information."
      fail
      return 1
    fi
@@ -66,7 +67,7 @@
 -    moc_ver=`$q/bin/moc 2>&1 -v|sed 's+^.*(Qt \(.*\))+\1+'`
 +  if check_avail "/usr/bin/moc"; then
 +    moc_ver=`/usr/bin/moc 2>&1 -v|sed 's+^.*(Qt \(.*\))+\1+'`
-     if (($?!=0)); then
+     if [ $? -ne 0 ]; then
        log_failure "not found"
        fail
 @@ -1081,7 +1069,6 @@
@@ -84,6 +85,6 @@
 -    --with-qt-dir=*)
 -      QTDIR=`echo $option | cut -d'=' -f2`
 -      ;;
-     --with-hal-dir=*)
-       INCHAL=`echo $option | cut -d'=' -f2`
+     --with-iasl=*)
+       IASL=`echo $option | cut -d'=' -f2`
        ;;
